"""Rules for building FFMpeg
"""

ffmpeg_copts = [
    "-w",
    "-fstrict-aliasing",
    "-std=c11",
    "-O3",
    "-g",
    "-fno-math-errno",
    "-fno-signed-zeros",
    "-fno-tree-vectorize",
    "-fomit-frame-pointer",
    "-pthread",
    "-D_FILE_OFFSET_BITS=64",
    "-D_GNU_SOURCE=1",
    "-D_ISOC99_SOURCE",
    "-D_LARGEFILE_SOURCE",
    "-D_POSIX_C_SOURCE=200112",
    "-D_REENTRANT",
    "-D_XOPEN_SOURCE=600",
    "-DHAVE_AV_CONFIG_H",
    "-DZLIB_CONST",
    "-Wall",
    "-Wdeclaration-after-statement",
    "-Wdisabled-optimization",
    "-Wempty-body",
    "-Werror=format-security",
    "-Werror=implicit-function-declaration",
    "-Werror=missing-prototypes",
    "-Werror=return-type",
    "-Werror=vla",
    "-Wformat",
    "-Wmissing-prototypes",
    "-Wno-format-zero-length",
    "-Wno-maybe-uninitialized",
    "-Wno-parentheses",
    "-Wno-pointer-sign",
    "-Wno-pointer-to-int-cast",
    "-Wno-switch",
    "-Wpointer-arith",
    "-Wredundant-decls",
    "-Wstrict-prototypes",
    "-Wtype-limits",
    "-Wundef",
    "-Wwrite-strings",
]

libavutil_shared_srcs = [
    "libavcodec/mathops.h",
    "libavutil/adler32.c",
    "libavutil/adler32.h",
    "libavutil/aes.c",
    "libavutil/aes.h",
    "libavutil/aes_ctr.c",
    "libavutil/aes_ctr.h",
    "libavutil/aes_internal.h",
    "libavutil/ambient_viewing_environment.c",
    "libavutil/ambient_viewing_environment.h",
    "libavutil/attributes.h",
    "libavutil/attributes_internal.h",
    "libavutil/audio_fifo.c",
    "libavutil/audio_fifo.h",
    "libavutil/avassert.h",
    "libavutil/avconfig.h",
    "libavutil/avsscanf.c",
    "libavutil/avstring.c",
    "libavutil/avstring.h",
    "libavutil/avutil.h",
    "libavutil/base64.c",
    "libavutil/base64.h",
    "libavutil/blowfish.c",
    "libavutil/blowfish.h",
    "libavutil/bprint.c",
    "libavutil/bprint.h",
    "libavutil/bswap.h",
    "libavutil/buffer.c",
    "libavutil/buffer.h",
    "libavutil/buffer_internal.h",
    "libavutil/camellia.c",
    "libavutil/camellia.h",
    "libavutil/cast5.c",
    "libavutil/cast5.h",
    "libavutil/channel_layout.c",
    "libavutil/channel_layout.h",
    "libavutil/colorspace.h",
    "libavutil/common.h",
    "libavutil/cpu.c",
    "libavutil/cpu.h",
    "libavutil/cpu_internal.h",
    "libavutil/crc.c",
    "libavutil/crc.h",
    "libavutil/csp.c",
    "libavutil/csp.h",
    "libavutil/cuda_check.h",
    "libavutil/des.c",
    "libavutil/des.h",
    "libavutil/detection_bbox.c",
    "libavutil/detection_bbox.h",
    "libavutil/dict.c",
    "libavutil/dict.h",
    "libavutil/dict_internal.h",
    "libavutil/display.c",
    "libavutil/display.h",
    "libavutil/dovi_meta.c",
    "libavutil/dovi_meta.h",
    "libavutil/downmix_info.c",
    "libavutil/downmix_info.h",
    "libavutil/dynarray.h",
    "libavutil/encryption_info.c",
    "libavutil/encryption_info.h",
    "libavutil/error.c",
    "libavutil/error.h",
    "libavutil/eval.c",
    "libavutil/eval.h",
    "libavutil/ffmath.h",
    "libavutil/ffversion.h",
    "libavutil/fifo.c",
    "libavutil/fifo.h",
    "libavutil/file.c",
    "libavutil/file.h",
    "libavutil/file_open.c",
    "libavutil/file_open.h",
    "libavutil/film_grain_params.c",
    "libavutil/film_grain_params.h",
    "libavutil/fixed_dsp.c",
    "libavutil/fixed_dsp.h",
    "libavutil/float2half.c",
    "libavutil/float2half.h",
    "libavutil/float_dsp.c",
    "libavutil/float_dsp.h",
    "libavutil/frame.c",
    "libavutil/frame.h",
    "libavutil/getenv_utf8.h",
    "libavutil/half2float.c",
    "libavutil/half2float.h",
    "libavutil/hash.c",
    "libavutil/hash.h",
    "libavutil/hdr_dynamic_metadata.c",
    "libavutil/hdr_dynamic_metadata.h",
    "libavutil/hdr_dynamic_vivid_metadata.c",
    "libavutil/hdr_dynamic_vivid_metadata.h",
    "libavutil/hmac.c",
    "libavutil/hmac.h",
    "libavutil/hwcontext.c",
    "libavutil/hwcontext.h",
    "libavutil/hwcontext_internal.h",
    "libavutil/imgutils.c",
    "libavutil/imgutils.h",
    "libavutil/imgutils_internal.h",
    "libavutil/integer.c",
    "libavutil/integer.h",
    "libavutil/internal.h",
    "libavutil/intfloat.h",
    "libavutil/intmath.c",
    "libavutil/intmath.h",
    "libavutil/intreadwrite.h",
    "libavutil/lfg.c",
    "libavutil/lfg.h",
    "libavutil/libm.h",
    "libavutil/lls.c",
    "libavutil/lls.h",
    "libavutil/log.c",
    "libavutil/log.h",
    "libavutil/log2_tab.c",
    "libavutil/lzo.c",
    "libavutil/lzo.h",
    "libavutil/macos_kperf.c",
    "libavutil/macos_kperf.h",
    "libavutil/macros.h",
    "libavutil/mastering_display_metadata.c",
    "libavutil/mastering_display_metadata.h",
    "libavutil/mathematics.c",
    "libavutil/mathematics.h",
    "libavutil/md5.c",
    "libavutil/md5.h",
    "libavutil/mem.c",
    "libavutil/mem.h",
    "libavutil/mem_internal.h",
    "libavutil/motion_vector.h",
    "libavutil/murmur3.c",
    "libavutil/murmur3.h",
    "libavutil/objc.h",
    "libavutil/opt.c",
    "libavutil/opt.h",
    "libavutil/parseutils.c",
    "libavutil/parseutils.h",
    "libavutil/pca.c",
    "libavutil/pca.h",
    "libavutil/pixdesc.c",
    "libavutil/pixdesc.h",
    "libavutil/pixelutils.c",
    "libavutil/pixelutils.h",
    "libavutil/pixfmt.h",
    "libavutil/qsort.h",
    "libavutil/random_seed.c",
    "libavutil/random_seed.h",
    "libavutil/rational.c",
    "libavutil/rational.h",
    "libavutil/rc4.c",
    "libavutil/rc4.h",
    "libavutil/replaygain.h",
    "libavutil/reverse.c",
    "libavutil/reverse.h",
    "libavutil/ripemd.c",
    "libavutil/ripemd.h",
    "libavutil/samplefmt.c",
    "libavutil/samplefmt.h",
    "libavutil/sha.c",
    "libavutil/sha.h",
    "libavutil/sha512.c",
    "libavutil/sha512.h",
    "libavutil/slicethread.c",
    "libavutil/slicethread.h",
    "libavutil/softfloat.h",
    "libavutil/softfloat_ieee754.h",
    "libavutil/softfloat_tables.h",
    "libavutil/spherical.c",
    "libavutil/spherical.h",
    "libavutil/stereo3d.c",
    "libavutil/stereo3d.h",
    "libavutil/tablegen.h",
    "libavutil/tea.c",
    "libavutil/tea.h",
    "libavutil/thread.h",
    "libavutil/threadmessage.c",
    "libavutil/threadmessage.h",
    "libavutil/time.c",
    "libavutil/time.h",
    "libavutil/time_internal.h",
    "libavutil/timecode.c",
    "libavutil/timecode.h",
    "libavutil/timer.h",
    "libavutil/timestamp.h",
    "libavutil/tree.c",
    "libavutil/tree.h",
    "libavutil/twofish.c",
    "libavutil/twofish.h",
    "libavutil/tx.c",
    "libavutil/tx.h",
    "libavutil/tx_priv.h",
    "libavutil/utils.c",
    "libavutil/uuid.c",
    "libavutil/uuid.h",
    "libavutil/version.c",
    "libavutil/version.h",
    "libavutil/version_major.h",
    "libavutil/video_enc_params.c",
    "libavutil/video_enc_params.h",
    "libavutil/wchar_filename.h",
    "libavutil/xga_font_data.c",
    "libavutil/xga_font_data.h",
    "libavutil/xtea.c",
    "libavutil/xtea.h",
]

libavutil_aarch64_srcs = []
# + glob([
#     "libavutil/aarch64/*.c",
#     "libavutil/aarch64/*.h",
#     "libavutil/aarch64/*.S",
# ])

libavutil_arm64_srcs = []
#  + glob([
#     "libavutil/arm/*.c",
#     "libavutil/arm/*.h",
#     "libavutil/arm/*.S",
# ])

libavutil_x86_srcs = [
    "libavcodec/x86/mathops.h",
    "libavutil/x86/asm.h",
    "libavutil/x86/bswap.h",
    "libavutil/x86/cpu.c",
    "libavutil/x86/cpu.h",
    "libavutil/x86/emms.h",
    "libavutil/x86/fixed_dsp_init.c",
    "libavutil/x86/float_dsp_init.c",
    "libavutil/x86/imgutils_init.c",
    "libavutil/x86/intmath.h",
    "libavutil/x86/intreadwrite.h",
    "libavutil/x86/lls_init.c",
    "libavutil/x86/pixelutils.h",
    "libavutil/x86/pixelutils_init.c",
    "libavutil/x86/timer.h",
    "libavutil/x86/tx_float_init.c",
    "libavutil/x86/w64xmmtest.h",
]

libavutil_srcs = libavutil_shared_srcs + select({
    "@platforms//cpu:aarch64": libavutil_aarch64_srcs,
    "@platforms//cpu:arm64": libavutil_arm64_srcs,
    "@platforms//cpu:x86_64": libavutil_x86_srcs,
    "//conditions:default": [],
})

libavutil_hdrs = [
    "libavutil/aarch64/cpu.h",
    "libavutil/ppc/util_altivec.h",
    "libavutil/loongarch/cpu.h",
    "libavutil/ppc/cpu.h",
    "libavutil/avutil.h",
    "libavutil/channel_layout.h",
    "libavutil/frame.h",
    "libavutil/samplefmt.h",
]

libswresample_shared_srcs = [
    "libavutil/attributes.h",
    "libavutil/avassert.h",
    # "libavutil/log.c",
    # "libavutil/log.h",
    # "libavutil/log2_tab.c",
    "libswresample/audioconvert.c",
    "libswresample/audioconvert.h",
    "libswresample/dither.c",
    # "libswresample/dither_template.c",
    # "libswresample/log2_tab.c",
    "libswresample/noise_shaping_data.c",
    "libswresample/options.c",
    "libswresample/rematrix.c",
    # "libswresample/rematrix_template.c",
    "libswresample/resample.c",
    "libswresample/resample.h",
    "libswresample/resample_dsp.c",
    # "libswresample/resample_template.c",
    # "libswresample/soxr_resample.c",
    "libswresample/swresample.c",
    "libswresample/swresample.h",
    "libswresample/swresample_frame.c",
    "libswresample/swresample_internal.h",
    "libswresample/version.c",
    "libswresample/version.h",
    "libswresample/version_major.h",
]

libswresample_aarch64_srcs = []

libswresample_arm64_srcs = []

libswresample_x86_srcs = [
    "libswresample/x86/audio_convert_init.c",
    "libswresample/x86/rematrix_init.c",
    "libswresample/x86/resample_init.c",
    "libswresample/x86/w64xmmtest.c",
]

libswresample_srcs = libswresample_shared_srcs + select({
    "@platforms//cpu:aarch64": libswresample_aarch64_srcs,
    "@platforms//cpu:arm64": libswresample_arm64_srcs,
    "@platforms//cpu:x86_64": libswresample_x86_srcs,
    "//conditions:default": [],
})

libswresample_hdrs = ["libswresample/swresample.h"]

libswresample_template_textual_hdrs = [
    "libswresample/noise_shaping_data.c",
    "libswresample/dither_template.c",
    "libswresample/resample_template.c",
    "libswresample/rematrix_template.c",
]

libswscale_template_shared_textual_hdrs = [
    "libswscale/bayer_template.c",
    "libswscale/rgb2rgb_template.c",
]

libswscale_template_x86_textual_hdrs = [
    "libswscale/x86/rgb2rgb_template.c",
    "libswscale/x86/swscale_template.c",
    "libswscale/x86/yuv2rgb_template.c",
]

libswscale_template_textual_hdrs = libswscale_template_shared_textual_hdrs + select({
    "@platforms//cpu:aarch64": [],
    "@platforms//cpu:arm64": [],
    "@platforms//cpu:x86_64": libswscale_template_x86_textual_hdrs,
    "//conditions:default": [],
})

libswscale_shared_srcs = [
    "libswscale/alphablend.c",
    "libswscale/gamma.c",
    "libswscale/half2float.c",
    "libswscale/hscale.c",
    "libswscale/hscale_fast_bilinear.c",
    "libswscale/input.c",
    "libswscale/log2_tab.c",
    "libswscale/options.c",
    "libswscale/output.c",
    "libswscale/rgb2rgb.c",
    "libswscale/rgb2rgb.h",
    "libswscale/slice.c",
    "libswscale/swscale.c",
    "libswscale/swscale.h",
    "libswscale/swscale_internal.h",
    "libswscale/swscale_unscaled.c",
    "libswscale/utils.c",
    "libswscale/version.c",
    "libswscale/version.h",
    "libswscale/version_major.h",
    "libswscale/vscale.c",
    "libswscale/yuv2rgb.c",
]

libswscale_x86_srcs = [
    "libswscale/x86/input.asmhscale_fast_bilinear_simd.c",
    "libswscale/x86/rgb2rgb.c",
    "libswscale/x86/swscale.c",
    "libswscale/x86/w64xmmtest.c",
    "libswscale/x86/yuv2rgb.c",
]

libswscale_srcs = libswscale_shared_srcs + select({
    "@platforms//cpu:aarch64": [],
    "@platforms//cpu:arm64": [],
    "@platforms//cpu:x86_64": libswresample_x86_srcs,
    "//conditions:default": [],
})

libswscale_hdrs = [
    "libswscale/swscale.h",
]
